// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gofins

import (
	"context"
	"encoding/binary"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClientConfig creates a new instance of MockClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientConfig {
	mock := &MockClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientConfig is an autogenerated mock type for the ClientConfig type
type MockClientConfig struct {
	mock.Mock
}

type MockClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientConfig) EXPECT() *MockClientConfig_Expecter {
	return &MockClientConfig_Expecter{mock: &_m.Mock}
}

// SetByteOrder provides a mock function for the type MockClientConfig
func (_mock *MockClientConfig) SetByteOrder(o binary.ByteOrder) {
	_mock.Called(o)
	return
}

// MockClientConfig_SetByteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetByteOrder'
type MockClientConfig_SetByteOrder_Call struct {
	*mock.Call
}

// SetByteOrder is a helper method to define mock.On call
//   - o binary.ByteOrder
func (_e *MockClientConfig_Expecter) SetByteOrder(o interface{}) *MockClientConfig_SetByteOrder_Call {
	return &MockClientConfig_SetByteOrder_Call{Call: _e.mock.On("SetByteOrder", o)}
}

func (_c *MockClientConfig_SetByteOrder_Call) Run(run func(o binary.ByteOrder)) *MockClientConfig_SetByteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 binary.ByteOrder
		if args[0] != nil {
			arg0 = args[0].(binary.ByteOrder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientConfig_SetByteOrder_Call) Return() *MockClientConfig_SetByteOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientConfig_SetByteOrder_Call) RunAndReturn(run func(o binary.ByteOrder)) *MockClientConfig_SetByteOrder_Call {
	_c.Run(run)
	return _c
}

// SetReadTimeout provides a mock function for the type MockClientConfig
func (_mock *MockClientConfig) SetReadTimeout(t time.Duration) {
	_mock.Called(t)
	return
}

// MockClientConfig_SetReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadTimeout'
type MockClientConfig_SetReadTimeout_Call struct {
	*mock.Call
}

// SetReadTimeout is a helper method to define mock.On call
//   - t time.Duration
func (_e *MockClientConfig_Expecter) SetReadTimeout(t interface{}) *MockClientConfig_SetReadTimeout_Call {
	return &MockClientConfig_SetReadTimeout_Call{Call: _e.mock.On("SetReadTimeout", t)}
}

func (_c *MockClientConfig_SetReadTimeout_Call) Run(run func(t time.Duration)) *MockClientConfig_SetReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientConfig_SetReadTimeout_Call) Return() *MockClientConfig_SetReadTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientConfig_SetReadTimeout_Call) RunAndReturn(run func(t time.Duration)) *MockClientConfig_SetReadTimeout_Call {
	_c.Run(run)
	return _c
}

// SetTimeoutMs provides a mock function for the type MockClientConfig
func (_mock *MockClientConfig) SetTimeoutMs(t uint) {
	_mock.Called(t)
	return
}

// MockClientConfig_SetTimeoutMs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeoutMs'
type MockClientConfig_SetTimeoutMs_Call struct {
	*mock.Call
}

// SetTimeoutMs is a helper method to define mock.On call
//   - t uint
func (_e *MockClientConfig_Expecter) SetTimeoutMs(t interface{}) *MockClientConfig_SetTimeoutMs_Call {
	return &MockClientConfig_SetTimeoutMs_Call{Call: _e.mock.On("SetTimeoutMs", t)}
}

func (_c *MockClientConfig_SetTimeoutMs_Call) Run(run func(t uint)) *MockClientConfig_SetTimeoutMs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientConfig_SetTimeoutMs_Call) Return() *MockClientConfig_SetTimeoutMs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientConfig_SetTimeoutMs_Call) RunAndReturn(run func(t uint)) *MockClientConfig_SetTimeoutMs_Call {
	_c.Run(run)
	return _c
}

// NewMockAutoReconnect creates a new instance of MockAutoReconnect. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoReconnect(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoReconnect {
	mock := &MockAutoReconnect{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAutoReconnect is an autogenerated mock type for the AutoReconnect type
type MockAutoReconnect struct {
	mock.Mock
}

type MockAutoReconnect_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoReconnect) EXPECT() *MockAutoReconnect_Expecter {
	return &MockAutoReconnect_Expecter{mock: &_m.Mock}
}

// DisableAutoReconnect provides a mock function for the type MockAutoReconnect
func (_mock *MockAutoReconnect) DisableAutoReconnect() {
	_mock.Called()
	return
}

// MockAutoReconnect_DisableAutoReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableAutoReconnect'
type MockAutoReconnect_DisableAutoReconnect_Call struct {
	*mock.Call
}

// DisableAutoReconnect is a helper method to define mock.On call
func (_e *MockAutoReconnect_Expecter) DisableAutoReconnect() *MockAutoReconnect_DisableAutoReconnect_Call {
	return &MockAutoReconnect_DisableAutoReconnect_Call{Call: _e.mock.On("DisableAutoReconnect")}
}

func (_c *MockAutoReconnect_DisableAutoReconnect_Call) Run(run func()) *MockAutoReconnect_DisableAutoReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAutoReconnect_DisableAutoReconnect_Call) Return() *MockAutoReconnect_DisableAutoReconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAutoReconnect_DisableAutoReconnect_Call) RunAndReturn(run func()) *MockAutoReconnect_DisableAutoReconnect_Call {
	_c.Run(run)
	return _c
}

// DisableDynamicLocalAddress provides a mock function for the type MockAutoReconnect
func (_mock *MockAutoReconnect) DisableDynamicLocalAddress() {
	_mock.Called()
	return
}

// MockAutoReconnect_DisableDynamicLocalAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDynamicLocalAddress'
type MockAutoReconnect_DisableDynamicLocalAddress_Call struct {
	*mock.Call
}

// DisableDynamicLocalAddress is a helper method to define mock.On call
func (_e *MockAutoReconnect_Expecter) DisableDynamicLocalAddress() *MockAutoReconnect_DisableDynamicLocalAddress_Call {
	return &MockAutoReconnect_DisableDynamicLocalAddress_Call{Call: _e.mock.On("DisableDynamicLocalAddress")}
}

func (_c *MockAutoReconnect_DisableDynamicLocalAddress_Call) Run(run func()) *MockAutoReconnect_DisableDynamicLocalAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAutoReconnect_DisableDynamicLocalAddress_Call) Return() *MockAutoReconnect_DisableDynamicLocalAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAutoReconnect_DisableDynamicLocalAddress_Call) RunAndReturn(run func()) *MockAutoReconnect_DisableDynamicLocalAddress_Call {
	_c.Run(run)
	return _c
}

// EnableAutoReconnect provides a mock function for the type MockAutoReconnect
func (_mock *MockAutoReconnect) EnableAutoReconnect(maxRetries int, initialDelay time.Duration) {
	_mock.Called(maxRetries, initialDelay)
	return
}

// MockAutoReconnect_EnableAutoReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableAutoReconnect'
type MockAutoReconnect_EnableAutoReconnect_Call struct {
	*mock.Call
}

// EnableAutoReconnect is a helper method to define mock.On call
//   - maxRetries int
//   - initialDelay time.Duration
func (_e *MockAutoReconnect_Expecter) EnableAutoReconnect(maxRetries interface{}, initialDelay interface{}) *MockAutoReconnect_EnableAutoReconnect_Call {
	return &MockAutoReconnect_EnableAutoReconnect_Call{Call: _e.mock.On("EnableAutoReconnect", maxRetries, initialDelay)}
}

func (_c *MockAutoReconnect_EnableAutoReconnect_Call) Run(run func(maxRetries int, initialDelay time.Duration)) *MockAutoReconnect_EnableAutoReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutoReconnect_EnableAutoReconnect_Call) Return() *MockAutoReconnect_EnableAutoReconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAutoReconnect_EnableAutoReconnect_Call) RunAndReturn(run func(maxRetries int, initialDelay time.Duration)) *MockAutoReconnect_EnableAutoReconnect_Call {
	_c.Run(run)
	return _c
}

// EnableDynamicLocalAddress provides a mock function for the type MockAutoReconnect
func (_mock *MockAutoReconnect) EnableDynamicLocalAddress() {
	_mock.Called()
	return
}

// MockAutoReconnect_EnableDynamicLocalAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDynamicLocalAddress'
type MockAutoReconnect_EnableDynamicLocalAddress_Call struct {
	*mock.Call
}

// EnableDynamicLocalAddress is a helper method to define mock.On call
func (_e *MockAutoReconnect_Expecter) EnableDynamicLocalAddress() *MockAutoReconnect_EnableDynamicLocalAddress_Call {
	return &MockAutoReconnect_EnableDynamicLocalAddress_Call{Call: _e.mock.On("EnableDynamicLocalAddress")}
}

func (_c *MockAutoReconnect_EnableDynamicLocalAddress_Call) Run(run func()) *MockAutoReconnect_EnableDynamicLocalAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAutoReconnect_EnableDynamicLocalAddress_Call) Return() *MockAutoReconnect_EnableDynamicLocalAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAutoReconnect_EnableDynamicLocalAddress_Call) RunAndReturn(run func()) *MockAutoReconnect_EnableDynamicLocalAddress_Call {
	_c.Run(run)
	return _c
}

// IsReconnecting provides a mock function for the type MockAutoReconnect
func (_mock *MockAutoReconnect) IsReconnecting() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReconnecting")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAutoReconnect_IsReconnecting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReconnecting'
type MockAutoReconnect_IsReconnecting_Call struct {
	*mock.Call
}

// IsReconnecting is a helper method to define mock.On call
func (_e *MockAutoReconnect_Expecter) IsReconnecting() *MockAutoReconnect_IsReconnecting_Call {
	return &MockAutoReconnect_IsReconnecting_Call{Call: _e.mock.On("IsReconnecting")}
}

func (_c *MockAutoReconnect_IsReconnecting_Call) Run(run func()) *MockAutoReconnect_IsReconnecting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAutoReconnect_IsReconnecting_Call) Return(b bool) *MockAutoReconnect_IsReconnecting_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAutoReconnect_IsReconnecting_Call) RunAndReturn(run func() bool) *MockAutoReconnect_IsReconnecting_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientHooks creates a new instance of MockClientHooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientHooks {
	mock := &MockClientHooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientHooks is an autogenerated mock type for the ClientHooks type
type MockClientHooks struct {
	mock.Mock
}

type MockClientHooks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientHooks) EXPECT() *MockClientHooks_Expecter {
	return &MockClientHooks_Expecter{mock: &_m.Mock}
}

// SetInterceptor provides a mock function for the type MockClientHooks
func (_mock *MockClientHooks) SetInterceptor(interceptor Interceptor) {
	_mock.Called(interceptor)
	return
}

// MockClientHooks_SetInterceptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInterceptor'
type MockClientHooks_SetInterceptor_Call struct {
	*mock.Call
}

// SetInterceptor is a helper method to define mock.On call
//   - interceptor Interceptor
func (_e *MockClientHooks_Expecter) SetInterceptor(interceptor interface{}) *MockClientHooks_SetInterceptor_Call {
	return &MockClientHooks_SetInterceptor_Call{Call: _e.mock.On("SetInterceptor", interceptor)}
}

func (_c *MockClientHooks_SetInterceptor_Call) Run(run func(interceptor Interceptor)) *MockClientHooks_SetInterceptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Interceptor
		if args[0] != nil {
			arg0 = args[0].(Interceptor)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientHooks_SetInterceptor_Call) Return() *MockClientHooks_SetInterceptor_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientHooks_SetInterceptor_Call) RunAndReturn(run func(interceptor Interceptor)) *MockClientHooks_SetInterceptor_Call {
	_c.Run(run)
	return _c
}

// Use provides a mock function for the type MockClientHooks
func (_mock *MockClientHooks) Use(plugins ...Plugin) error {
	var tmpRet mock.Arguments
	if len(plugins) > 0 {
		tmpRet = _mock.Called(plugins)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...Plugin) error); ok {
		r0 = returnFunc(plugins...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientHooks_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockClientHooks_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - plugins ...Plugin
func (_e *MockClientHooks_Expecter) Use(plugins ...interface{}) *MockClientHooks_Use_Call {
	return &MockClientHooks_Use_Call{Call: _e.mock.On("Use",
		append([]interface{}{}, plugins...)...)}
}

func (_c *MockClientHooks_Use_Call) Run(run func(plugins ...Plugin)) *MockClientHooks_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Plugin
		var variadicArgs []Plugin
		if len(args) > 0 {
			variadicArgs = args[0].([]Plugin)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockClientHooks_Use_Call) Return(err error) *MockClientHooks_Use_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientHooks_Use_Call) RunAndReturn(run func(plugins ...Plugin) error) *MockClientHooks_Use_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientLifecycle creates a new instance of MockClientLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientLifecycle {
	mock := &MockClientLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientLifecycle is an autogenerated mock type for the ClientLifecycle type
type MockClientLifecycle struct {
	mock.Mock
}

type MockClientLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientLifecycle) EXPECT() *MockClientLifecycle_Expecter {
	return &MockClientLifecycle_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClientLifecycle
func (_mock *MockClientLifecycle) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientLifecycle_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientLifecycle_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClientLifecycle_Expecter) Close() *MockClientLifecycle_Close_Call {
	return &MockClientLifecycle_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClientLifecycle_Close_Call) Run(run func()) *MockClientLifecycle_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientLifecycle_Close_Call) Return(err error) *MockClientLifecycle_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientLifecycle_Close_Call) RunAndReturn(run func() error) *MockClientLifecycle_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsClosed provides a mock function for the type MockClientLifecycle
func (_mock *MockClientLifecycle) IsClosed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClientLifecycle_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type MockClientLifecycle_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *MockClientLifecycle_Expecter) IsClosed() *MockClientLifecycle_IsClosed_Call {
	return &MockClientLifecycle_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *MockClientLifecycle_IsClosed_Call) Run(run func()) *MockClientLifecycle_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientLifecycle_IsClosed_Call) Return(b bool) *MockClientLifecycle_IsClosed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClientLifecycle_IsClosed_Call) RunAndReturn(run func() bool) *MockClientLifecycle_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockClientLifecycle
func (_mock *MockClientLifecycle) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientLifecycle_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockClientLifecycle_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockClientLifecycle_Expecter) Shutdown() *MockClientLifecycle_Shutdown_Call {
	return &MockClientLifecycle_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockClientLifecycle_Shutdown_Call) Run(run func()) *MockClientLifecycle_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientLifecycle_Shutdown_Call) Return(err error) *MockClientLifecycle_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientLifecycle_Shutdown_Call) RunAndReturn(run func() error) *MockClientLifecycle_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientReader creates a new instance of MockClientReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientReader {
	mock := &MockClientReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientReader is an autogenerated mock type for the ClientReader type
type MockClientReader struct {
	mock.Mock
}

type MockClientReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientReader) EXPECT() *MockClientReader_Expecter {
	return &MockClientReader_Expecter{mock: &_m.Mock}
}

// ReadBits provides a mock function for the type MockClientReader
func (_mock *MockClientReader) ReadBits(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16) ([]bool, error) {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadBits")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, uint16) ([]bool, error)); ok {
		return returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, uint16) []bool); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, byte, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReader_ReadBits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBits'
type MockClientReader_ReadBits_Call struct {
	*mock.Call
}

// ReadBits is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
//   - readCount uint16
func (_e *MockClientReader_Expecter) ReadBits(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}, readCount interface{}) *MockClientReader_ReadBits_Call {
	return &MockClientReader_ReadBits_Call{Call: _e.mock.On("ReadBits", ctx, memoryArea, address, bitOffset, readCount)}
}

func (_c *MockClientReader_ReadBits_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16)) *MockClientReader_ReadBits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		var arg4 uint16
		if args[4] != nil {
			arg4 = args[4].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClientReader_ReadBits_Call) Return(bools []bool, err error) *MockClientReader_ReadBits_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockClientReader_ReadBits_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16) ([]bool, error)) *MockClientReader_ReadBits_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBytes provides a mock function for the type MockClientReader
func (_mock *MockClientReader) ReadBytes(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]byte, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) ([]byte, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) []byte); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReader_ReadBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBytes'
type MockClientReader_ReadBytes_Call struct {
	*mock.Call
}

// ReadBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockClientReader_Expecter) ReadBytes(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockClientReader_ReadBytes_Call {
	return &MockClientReader_ReadBytes_Call{Call: _e.mock.On("ReadBytes", ctx, memoryArea, address, readCount)}
}

func (_c *MockClientReader_ReadBytes_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockClientReader_ReadBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientReader_ReadBytes_Call) Return(bytes []byte, err error) *MockClientReader_ReadBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClientReader_ReadBytes_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]byte, error)) *MockClientReader_ReadBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClock provides a mock function for the type MockClientReader
func (_mock *MockClientReader) ReadClock(ctx context.Context) (*time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadClock")
	}

	var r0 *time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *time.Time); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReader_ReadClock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClock'
type MockClientReader_ReadClock_Call struct {
	*mock.Call
}

// ReadClock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientReader_Expecter) ReadClock(ctx interface{}) *MockClientReader_ReadClock_Call {
	return &MockClientReader_ReadClock_Call{Call: _e.mock.On("ReadClock", ctx)}
}

func (_c *MockClientReader_ReadClock_Call) Run(run func(ctx context.Context)) *MockClientReader_ReadClock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientReader_ReadClock_Call) Return(time1 *time.Time, err error) *MockClientReader_ReadClock_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockClientReader_ReadClock_Call) RunAndReturn(run func(ctx context.Context) (*time.Time, error)) *MockClientReader_ReadClock_Call {
	_c.Call.Return(run)
	return _c
}

// ReadString provides a mock function for the type MockClientReader
func (_mock *MockClientReader) ReadString(ctx context.Context, memoryArea byte, address uint16, readCount uint16) (string, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) (string, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) string); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReader_ReadString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadString'
type MockClientReader_ReadString_Call struct {
	*mock.Call
}

// ReadString is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockClientReader_Expecter) ReadString(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockClientReader_ReadString_Call {
	return &MockClientReader_ReadString_Call{Call: _e.mock.On("ReadString", ctx, memoryArea, address, readCount)}
}

func (_c *MockClientReader_ReadString_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockClientReader_ReadString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientReader_ReadString_Call) Return(s string, err error) *MockClientReader_ReadString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClientReader_ReadString_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) (string, error)) *MockClientReader_ReadString_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWords provides a mock function for the type MockClientReader
func (_mock *MockClientReader) ReadWords(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]uint16, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadWords")
	}

	var r0 []uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) ([]uint16, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) []uint16); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReader_ReadWords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWords'
type MockClientReader_ReadWords_Call struct {
	*mock.Call
}

// ReadWords is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockClientReader_Expecter) ReadWords(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockClientReader_ReadWords_Call {
	return &MockClientReader_ReadWords_Call{Call: _e.mock.On("ReadWords", ctx, memoryArea, address, readCount)}
}

func (_c *MockClientReader_ReadWords_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockClientReader_ReadWords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientReader_ReadWords_Call) Return(uint16s []uint16, err error) *MockClientReader_ReadWords_Call {
	_c.Call.Return(uint16s, err)
	return _c
}

func (_c *MockClientReader_ReadWords_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]uint16, error)) *MockClientReader_ReadWords_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientWriter creates a new instance of MockClientWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWriter {
	mock := &MockClientWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientWriter is an autogenerated mock type for the ClientWriter type
type MockClientWriter struct {
	mock.Mock
}

type MockClientWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWriter) EXPECT() *MockClientWriter_Expecter {
	return &MockClientWriter_Expecter{mock: &_m.Mock}
}

// ResetBit provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) ResetBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for ResetBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_ResetBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetBit'
type MockClientWriter_ResetBit_Call struct {
	*mock.Call
}

// ResetBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockClientWriter_Expecter) ResetBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockClientWriter_ResetBit_Call {
	return &MockClientWriter_ResetBit_Call{Call: _e.mock.On("ResetBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockClientWriter_ResetBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockClientWriter_ResetBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_ResetBit_Call) Return(err error) *MockClientWriter_ResetBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_ResetBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockClientWriter_ResetBit_Call {
	_c.Call.Return(run)
	return _c
}

// SetBit provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) SetBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for SetBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_SetBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBit'
type MockClientWriter_SetBit_Call struct {
	*mock.Call
}

// SetBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockClientWriter_Expecter) SetBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockClientWriter_SetBit_Call {
	return &MockClientWriter_SetBit_Call{Call: _e.mock.On("SetBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockClientWriter_SetBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockClientWriter_SetBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_SetBit_Call) Return(err error) *MockClientWriter_SetBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_SetBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockClientWriter_SetBit_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleBit provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) ToggleBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for ToggleBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_ToggleBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleBit'
type MockClientWriter_ToggleBit_Call struct {
	*mock.Call
}

// ToggleBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockClientWriter_Expecter) ToggleBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockClientWriter_ToggleBit_Call {
	return &MockClientWriter_ToggleBit_Call{Call: _e.mock.On("ToggleBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockClientWriter_ToggleBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockClientWriter_ToggleBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_ToggleBit_Call) Return(err error) *MockClientWriter_ToggleBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_ToggleBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockClientWriter_ToggleBit_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBits provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) WriteBits(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteBits")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, []bool) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_WriteBits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBits'
type MockClientWriter_WriteBits_Call struct {
	*mock.Call
}

// WriteBits is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
//   - data []bool
func (_e *MockClientWriter_Expecter) WriteBits(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}, data interface{}) *MockClientWriter_WriteBits_Call {
	return &MockClientWriter_WriteBits_Call{Call: _e.mock.On("WriteBits", ctx, memoryArea, address, bitOffset, data)}
}

func (_c *MockClientWriter_WriteBits_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool)) *MockClientWriter_WriteBits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		var arg4 []bool
		if args[4] != nil {
			arg4 = args[4].([]bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClientWriter_WriteBits_Call) Return(err error) *MockClientWriter_WriteBits_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_WriteBits_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool) error) *MockClientWriter_WriteBits_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBytes provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) WriteBytes(ctx context.Context, memoryArea byte, address uint16, b []byte) error {
	ret := _mock.Called(ctx, memoryArea, address, b)

	if len(ret) == 0 {
		panic("no return value specified for WriteBytes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, []byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_WriteBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBytes'
type MockClientWriter_WriteBytes_Call struct {
	*mock.Call
}

// WriteBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - b []byte
func (_e *MockClientWriter_Expecter) WriteBytes(ctx interface{}, memoryArea interface{}, address interface{}, b interface{}) *MockClientWriter_WriteBytes_Call {
	return &MockClientWriter_WriteBytes_Call{Call: _e.mock.On("WriteBytes", ctx, memoryArea, address, b)}
}

func (_c *MockClientWriter_WriteBytes_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, b []byte)) *MockClientWriter_WriteBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_WriteBytes_Call) Return(err error) *MockClientWriter_WriteBytes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_WriteBytes_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, b []byte) error) *MockClientWriter_WriteBytes_Call {
	_c.Call.Return(run)
	return _c
}

// WriteString provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) WriteString(ctx context.Context, memoryArea byte, address uint16, s string) error {
	ret := _mock.Called(ctx, memoryArea, address, s)

	if len(ret) == 0 {
		panic("no return value specified for WriteString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, string) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_WriteString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteString'
type MockClientWriter_WriteString_Call struct {
	*mock.Call
}

// WriteString is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - s string
func (_e *MockClientWriter_Expecter) WriteString(ctx interface{}, memoryArea interface{}, address interface{}, s interface{}) *MockClientWriter_WriteString_Call {
	return &MockClientWriter_WriteString_Call{Call: _e.mock.On("WriteString", ctx, memoryArea, address, s)}
}

func (_c *MockClientWriter_WriteString_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, s string)) *MockClientWriter_WriteString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_WriteString_Call) Return(err error) *MockClientWriter_WriteString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_WriteString_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, s string) error) *MockClientWriter_WriteString_Call {
	_c.Call.Return(run)
	return _c
}

// WriteWords provides a mock function for the type MockClientWriter
func (_mock *MockClientWriter) WriteWords(ctx context.Context, memoryArea byte, address uint16, data []uint16) error {
	ret := _mock.Called(ctx, memoryArea, address, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteWords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, []uint16) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientWriter_WriteWords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteWords'
type MockClientWriter_WriteWords_Call struct {
	*mock.Call
}

// WriteWords is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - data []uint16
func (_e *MockClientWriter_Expecter) WriteWords(ctx interface{}, memoryArea interface{}, address interface{}, data interface{}) *MockClientWriter_WriteWords_Call {
	return &MockClientWriter_WriteWords_Call{Call: _e.mock.On("WriteWords", ctx, memoryArea, address, data)}
}

func (_c *MockClientWriter_WriteWords_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, data []uint16)) *MockClientWriter_WriteWords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 []uint16
		if args[3] != nil {
			arg3 = args[3].([]uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientWriter_WriteWords_Call) Return(err error) *MockClientWriter_WriteWords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientWriter_WriteWords_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, data []uint16) error) *MockClientWriter_WriteWords_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFINSClient creates a new instance of MockFINSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFINSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFINSClient {
	mock := &MockFINSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFINSClient is an autogenerated mock type for the FINSClient type
type MockFINSClient struct {
	mock.Mock
}

type MockFINSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFINSClient) EXPECT() *MockFINSClient_Expecter {
	return &MockFINSClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFINSClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) Close() *MockFINSClient_Close_Call {
	return &MockFINSClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFINSClient_Close_Call) Run(run func()) *MockFINSClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_Close_Call) Return(err error) *MockFINSClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_Close_Call) RunAndReturn(run func() error) *MockFINSClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DisableAutoReconnect provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) DisableAutoReconnect() {
	_mock.Called()
	return
}

// MockFINSClient_DisableAutoReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableAutoReconnect'
type MockFINSClient_DisableAutoReconnect_Call struct {
	*mock.Call
}

// DisableAutoReconnect is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) DisableAutoReconnect() *MockFINSClient_DisableAutoReconnect_Call {
	return &MockFINSClient_DisableAutoReconnect_Call{Call: _e.mock.On("DisableAutoReconnect")}
}

func (_c *MockFINSClient_DisableAutoReconnect_Call) Run(run func()) *MockFINSClient_DisableAutoReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_DisableAutoReconnect_Call) Return() *MockFINSClient_DisableAutoReconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_DisableAutoReconnect_Call) RunAndReturn(run func()) *MockFINSClient_DisableAutoReconnect_Call {
	_c.Run(run)
	return _c
}

// DisableDynamicLocalAddress provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) DisableDynamicLocalAddress() {
	_mock.Called()
	return
}

// MockFINSClient_DisableDynamicLocalAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDynamicLocalAddress'
type MockFINSClient_DisableDynamicLocalAddress_Call struct {
	*mock.Call
}

// DisableDynamicLocalAddress is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) DisableDynamicLocalAddress() *MockFINSClient_DisableDynamicLocalAddress_Call {
	return &MockFINSClient_DisableDynamicLocalAddress_Call{Call: _e.mock.On("DisableDynamicLocalAddress")}
}

func (_c *MockFINSClient_DisableDynamicLocalAddress_Call) Run(run func()) *MockFINSClient_DisableDynamicLocalAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_DisableDynamicLocalAddress_Call) Return() *MockFINSClient_DisableDynamicLocalAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_DisableDynamicLocalAddress_Call) RunAndReturn(run func()) *MockFINSClient_DisableDynamicLocalAddress_Call {
	_c.Run(run)
	return _c
}

// EnableAutoReconnect provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) EnableAutoReconnect(maxRetries int, initialDelay time.Duration) {
	_mock.Called(maxRetries, initialDelay)
	return
}

// MockFINSClient_EnableAutoReconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableAutoReconnect'
type MockFINSClient_EnableAutoReconnect_Call struct {
	*mock.Call
}

// EnableAutoReconnect is a helper method to define mock.On call
//   - maxRetries int
//   - initialDelay time.Duration
func (_e *MockFINSClient_Expecter) EnableAutoReconnect(maxRetries interface{}, initialDelay interface{}) *MockFINSClient_EnableAutoReconnect_Call {
	return &MockFINSClient_EnableAutoReconnect_Call{Call: _e.mock.On("EnableAutoReconnect", maxRetries, initialDelay)}
}

func (_c *MockFINSClient_EnableAutoReconnect_Call) Run(run func(maxRetries int, initialDelay time.Duration)) *MockFINSClient_EnableAutoReconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFINSClient_EnableAutoReconnect_Call) Return() *MockFINSClient_EnableAutoReconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_EnableAutoReconnect_Call) RunAndReturn(run func(maxRetries int, initialDelay time.Duration)) *MockFINSClient_EnableAutoReconnect_Call {
	_c.Run(run)
	return _c
}

// EnableDynamicLocalAddress provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) EnableDynamicLocalAddress() {
	_mock.Called()
	return
}

// MockFINSClient_EnableDynamicLocalAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDynamicLocalAddress'
type MockFINSClient_EnableDynamicLocalAddress_Call struct {
	*mock.Call
}

// EnableDynamicLocalAddress is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) EnableDynamicLocalAddress() *MockFINSClient_EnableDynamicLocalAddress_Call {
	return &MockFINSClient_EnableDynamicLocalAddress_Call{Call: _e.mock.On("EnableDynamicLocalAddress")}
}

func (_c *MockFINSClient_EnableDynamicLocalAddress_Call) Run(run func()) *MockFINSClient_EnableDynamicLocalAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_EnableDynamicLocalAddress_Call) Return() *MockFINSClient_EnableDynamicLocalAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_EnableDynamicLocalAddress_Call) RunAndReturn(run func()) *MockFINSClient_EnableDynamicLocalAddress_Call {
	_c.Run(run)
	return _c
}

// IsClosed provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) IsClosed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFINSClient_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type MockFINSClient_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) IsClosed() *MockFINSClient_IsClosed_Call {
	return &MockFINSClient_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *MockFINSClient_IsClosed_Call) Run(run func()) *MockFINSClient_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_IsClosed_Call) Return(b bool) *MockFINSClient_IsClosed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFINSClient_IsClosed_Call) RunAndReturn(run func() bool) *MockFINSClient_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}

// IsReconnecting provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) IsReconnecting() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReconnecting")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFINSClient_IsReconnecting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReconnecting'
type MockFINSClient_IsReconnecting_Call struct {
	*mock.Call
}

// IsReconnecting is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) IsReconnecting() *MockFINSClient_IsReconnecting_Call {
	return &MockFINSClient_IsReconnecting_Call{Call: _e.mock.On("IsReconnecting")}
}

func (_c *MockFINSClient_IsReconnecting_Call) Run(run func()) *MockFINSClient_IsReconnecting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_IsReconnecting_Call) Return(b bool) *MockFINSClient_IsReconnecting_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFINSClient_IsReconnecting_Call) RunAndReturn(run func() bool) *MockFINSClient_IsReconnecting_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBits provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ReadBits(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16) ([]bool, error) {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadBits")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, uint16) ([]bool, error)); ok {
		return returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, uint16) []bool); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, byte, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, bitOffset, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFINSClient_ReadBits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBits'
type MockFINSClient_ReadBits_Call struct {
	*mock.Call
}

// ReadBits is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
//   - readCount uint16
func (_e *MockFINSClient_Expecter) ReadBits(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}, readCount interface{}) *MockFINSClient_ReadBits_Call {
	return &MockFINSClient_ReadBits_Call{Call: _e.mock.On("ReadBits", ctx, memoryArea, address, bitOffset, readCount)}
}

func (_c *MockFINSClient_ReadBits_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16)) *MockFINSClient_ReadBits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		var arg4 uint16
		if args[4] != nil {
			arg4 = args[4].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFINSClient_ReadBits_Call) Return(bools []bool, err error) *MockFINSClient_ReadBits_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockFINSClient_ReadBits_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, readCount uint16) ([]bool, error)) *MockFINSClient_ReadBits_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBytes provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ReadBytes(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]byte, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) ([]byte, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) []byte); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFINSClient_ReadBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBytes'
type MockFINSClient_ReadBytes_Call struct {
	*mock.Call
}

// ReadBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockFINSClient_Expecter) ReadBytes(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockFINSClient_ReadBytes_Call {
	return &MockFINSClient_ReadBytes_Call{Call: _e.mock.On("ReadBytes", ctx, memoryArea, address, readCount)}
}

func (_c *MockFINSClient_ReadBytes_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockFINSClient_ReadBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_ReadBytes_Call) Return(bytes []byte, err error) *MockFINSClient_ReadBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFINSClient_ReadBytes_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]byte, error)) *MockFINSClient_ReadBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClock provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ReadClock(ctx context.Context) (*time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadClock")
	}

	var r0 *time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *time.Time); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFINSClient_ReadClock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClock'
type MockFINSClient_ReadClock_Call struct {
	*mock.Call
}

// ReadClock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFINSClient_Expecter) ReadClock(ctx interface{}) *MockFINSClient_ReadClock_Call {
	return &MockFINSClient_ReadClock_Call{Call: _e.mock.On("ReadClock", ctx)}
}

func (_c *MockFINSClient_ReadClock_Call) Run(run func(ctx context.Context)) *MockFINSClient_ReadClock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFINSClient_ReadClock_Call) Return(time1 *time.Time, err error) *MockFINSClient_ReadClock_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockFINSClient_ReadClock_Call) RunAndReturn(run func(ctx context.Context) (*time.Time, error)) *MockFINSClient_ReadClock_Call {
	_c.Call.Return(run)
	return _c
}

// ReadString provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ReadString(ctx context.Context, memoryArea byte, address uint16, readCount uint16) (string, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) (string, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) string); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFINSClient_ReadString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadString'
type MockFINSClient_ReadString_Call struct {
	*mock.Call
}

// ReadString is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockFINSClient_Expecter) ReadString(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockFINSClient_ReadString_Call {
	return &MockFINSClient_ReadString_Call{Call: _e.mock.On("ReadString", ctx, memoryArea, address, readCount)}
}

func (_c *MockFINSClient_ReadString_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockFINSClient_ReadString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_ReadString_Call) Return(s string, err error) *MockFINSClient_ReadString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFINSClient_ReadString_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) (string, error)) *MockFINSClient_ReadString_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWords provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ReadWords(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]uint16, error) {
	ret := _mock.Called(ctx, memoryArea, address, readCount)

	if len(ret) == 0 {
		panic("no return value specified for ReadWords")
	}

	var r0 []uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) ([]uint16, error)); ok {
		return returnFunc(ctx, memoryArea, address, readCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, uint16) []uint16); ok {
		r0 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, byte, uint16, uint16) error); ok {
		r1 = returnFunc(ctx, memoryArea, address, readCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFINSClient_ReadWords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWords'
type MockFINSClient_ReadWords_Call struct {
	*mock.Call
}

// ReadWords is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - readCount uint16
func (_e *MockFINSClient_Expecter) ReadWords(ctx interface{}, memoryArea interface{}, address interface{}, readCount interface{}) *MockFINSClient_ReadWords_Call {
	return &MockFINSClient_ReadWords_Call{Call: _e.mock.On("ReadWords", ctx, memoryArea, address, readCount)}
}

func (_c *MockFINSClient_ReadWords_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16)) *MockFINSClient_ReadWords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 uint16
		if args[3] != nil {
			arg3 = args[3].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_ReadWords_Call) Return(uint16s []uint16, err error) *MockFINSClient_ReadWords_Call {
	_c.Call.Return(uint16s, err)
	return _c
}

func (_c *MockFINSClient_ReadWords_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, readCount uint16) ([]uint16, error)) *MockFINSClient_ReadWords_Call {
	_c.Call.Return(run)
	return _c
}

// ResetBit provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ResetBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for ResetBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_ResetBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetBit'
type MockFINSClient_ResetBit_Call struct {
	*mock.Call
}

// ResetBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockFINSClient_Expecter) ResetBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockFINSClient_ResetBit_Call {
	return &MockFINSClient_ResetBit_Call{Call: _e.mock.On("ResetBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockFINSClient_ResetBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockFINSClient_ResetBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_ResetBit_Call) Return(err error) *MockFINSClient_ResetBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_ResetBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockFINSClient_ResetBit_Call {
	_c.Call.Return(run)
	return _c
}

// SetBit provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) SetBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for SetBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_SetBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBit'
type MockFINSClient_SetBit_Call struct {
	*mock.Call
}

// SetBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockFINSClient_Expecter) SetBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockFINSClient_SetBit_Call {
	return &MockFINSClient_SetBit_Call{Call: _e.mock.On("SetBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockFINSClient_SetBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockFINSClient_SetBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_SetBit_Call) Return(err error) *MockFINSClient_SetBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_SetBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockFINSClient_SetBit_Call {
	_c.Call.Return(run)
	return _c
}

// SetByteOrder provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) SetByteOrder(o binary.ByteOrder) {
	_mock.Called(o)
	return
}

// MockFINSClient_SetByteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetByteOrder'
type MockFINSClient_SetByteOrder_Call struct {
	*mock.Call
}

// SetByteOrder is a helper method to define mock.On call
//   - o binary.ByteOrder
func (_e *MockFINSClient_Expecter) SetByteOrder(o interface{}) *MockFINSClient_SetByteOrder_Call {
	return &MockFINSClient_SetByteOrder_Call{Call: _e.mock.On("SetByteOrder", o)}
}

func (_c *MockFINSClient_SetByteOrder_Call) Run(run func(o binary.ByteOrder)) *MockFINSClient_SetByteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 binary.ByteOrder
		if args[0] != nil {
			arg0 = args[0].(binary.ByteOrder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFINSClient_SetByteOrder_Call) Return() *MockFINSClient_SetByteOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_SetByteOrder_Call) RunAndReturn(run func(o binary.ByteOrder)) *MockFINSClient_SetByteOrder_Call {
	_c.Run(run)
	return _c
}

// SetInterceptor provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) SetInterceptor(interceptor Interceptor) {
	_mock.Called(interceptor)
	return
}

// MockFINSClient_SetInterceptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInterceptor'
type MockFINSClient_SetInterceptor_Call struct {
	*mock.Call
}

// SetInterceptor is a helper method to define mock.On call
//   - interceptor Interceptor
func (_e *MockFINSClient_Expecter) SetInterceptor(interceptor interface{}) *MockFINSClient_SetInterceptor_Call {
	return &MockFINSClient_SetInterceptor_Call{Call: _e.mock.On("SetInterceptor", interceptor)}
}

func (_c *MockFINSClient_SetInterceptor_Call) Run(run func(interceptor Interceptor)) *MockFINSClient_SetInterceptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Interceptor
		if args[0] != nil {
			arg0 = args[0].(Interceptor)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFINSClient_SetInterceptor_Call) Return() *MockFINSClient_SetInterceptor_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_SetInterceptor_Call) RunAndReturn(run func(interceptor Interceptor)) *MockFINSClient_SetInterceptor_Call {
	_c.Run(run)
	return _c
}

// SetReadTimeout provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) SetReadTimeout(t time.Duration) {
	_mock.Called(t)
	return
}

// MockFINSClient_SetReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadTimeout'
type MockFINSClient_SetReadTimeout_Call struct {
	*mock.Call
}

// SetReadTimeout is a helper method to define mock.On call
//   - t time.Duration
func (_e *MockFINSClient_Expecter) SetReadTimeout(t interface{}) *MockFINSClient_SetReadTimeout_Call {
	return &MockFINSClient_SetReadTimeout_Call{Call: _e.mock.On("SetReadTimeout", t)}
}

func (_c *MockFINSClient_SetReadTimeout_Call) Run(run func(t time.Duration)) *MockFINSClient_SetReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFINSClient_SetReadTimeout_Call) Return() *MockFINSClient_SetReadTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_SetReadTimeout_Call) RunAndReturn(run func(t time.Duration)) *MockFINSClient_SetReadTimeout_Call {
	_c.Run(run)
	return _c
}

// SetTimeoutMs provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) SetTimeoutMs(t uint) {
	_mock.Called(t)
	return
}

// MockFINSClient_SetTimeoutMs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeoutMs'
type MockFINSClient_SetTimeoutMs_Call struct {
	*mock.Call
}

// SetTimeoutMs is a helper method to define mock.On call
//   - t uint
func (_e *MockFINSClient_Expecter) SetTimeoutMs(t interface{}) *MockFINSClient_SetTimeoutMs_Call {
	return &MockFINSClient_SetTimeoutMs_Call{Call: _e.mock.On("SetTimeoutMs", t)}
}

func (_c *MockFINSClient_SetTimeoutMs_Call) Run(run func(t uint)) *MockFINSClient_SetTimeoutMs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFINSClient_SetTimeoutMs_Call) Return() *MockFINSClient_SetTimeoutMs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFINSClient_SetTimeoutMs_Call) RunAndReturn(run func(t uint)) *MockFINSClient_SetTimeoutMs_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockFINSClient_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockFINSClient_Expecter) Shutdown() *MockFINSClient_Shutdown_Call {
	return &MockFINSClient_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockFINSClient_Shutdown_Call) Run(run func()) *MockFINSClient_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFINSClient_Shutdown_Call) Return(err error) *MockFINSClient_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_Shutdown_Call) RunAndReturn(run func() error) *MockFINSClient_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleBit provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) ToggleBit(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset)

	if len(ret) == 0 {
		panic("no return value specified for ToggleBit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_ToggleBit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleBit'
type MockFINSClient_ToggleBit_Call struct {
	*mock.Call
}

// ToggleBit is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
func (_e *MockFINSClient_Expecter) ToggleBit(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}) *MockFINSClient_ToggleBit_Call {
	return &MockFINSClient_ToggleBit_Call{Call: _e.mock.On("ToggleBit", ctx, memoryArea, address, bitOffset)}
}

func (_c *MockFINSClient_ToggleBit_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte)) *MockFINSClient_ToggleBit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_ToggleBit_Call) Return(err error) *MockFINSClient_ToggleBit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_ToggleBit_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte) error) *MockFINSClient_ToggleBit_Call {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) Use(plugins ...Plugin) error {
	var tmpRet mock.Arguments
	if len(plugins) > 0 {
		tmpRet = _mock.Called(plugins)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...Plugin) error); ok {
		r0 = returnFunc(plugins...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockFINSClient_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - plugins ...Plugin
func (_e *MockFINSClient_Expecter) Use(plugins ...interface{}) *MockFINSClient_Use_Call {
	return &MockFINSClient_Use_Call{Call: _e.mock.On("Use",
		append([]interface{}{}, plugins...)...)}
}

func (_c *MockFINSClient_Use_Call) Run(run func(plugins ...Plugin)) *MockFINSClient_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Plugin
		var variadicArgs []Plugin
		if len(args) > 0 {
			variadicArgs = args[0].([]Plugin)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockFINSClient_Use_Call) Return(err error) *MockFINSClient_Use_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_Use_Call) RunAndReturn(run func(plugins ...Plugin) error) *MockFINSClient_Use_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBits provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) WriteBits(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool) error {
	ret := _mock.Called(ctx, memoryArea, address, bitOffset, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteBits")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, byte, []bool) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, bitOffset, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_WriteBits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBits'
type MockFINSClient_WriteBits_Call struct {
	*mock.Call
}

// WriteBits is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - bitOffset byte
//   - data []bool
func (_e *MockFINSClient_Expecter) WriteBits(ctx interface{}, memoryArea interface{}, address interface{}, bitOffset interface{}, data interface{}) *MockFINSClient_WriteBits_Call {
	return &MockFINSClient_WriteBits_Call{Call: _e.mock.On("WriteBits", ctx, memoryArea, address, bitOffset, data)}
}

func (_c *MockFINSClient_WriteBits_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool)) *MockFINSClient_WriteBits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 byte
		if args[3] != nil {
			arg3 = args[3].(byte)
		}
		var arg4 []bool
		if args[4] != nil {
			arg4 = args[4].([]bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFINSClient_WriteBits_Call) Return(err error) *MockFINSClient_WriteBits_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_WriteBits_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, bitOffset byte, data []bool) error) *MockFINSClient_WriteBits_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBytes provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) WriteBytes(ctx context.Context, memoryArea byte, address uint16, b []byte) error {
	ret := _mock.Called(ctx, memoryArea, address, b)

	if len(ret) == 0 {
		panic("no return value specified for WriteBytes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, []byte) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_WriteBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBytes'
type MockFINSClient_WriteBytes_Call struct {
	*mock.Call
}

// WriteBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - b []byte
func (_e *MockFINSClient_Expecter) WriteBytes(ctx interface{}, memoryArea interface{}, address interface{}, b interface{}) *MockFINSClient_WriteBytes_Call {
	return &MockFINSClient_WriteBytes_Call{Call: _e.mock.On("WriteBytes", ctx, memoryArea, address, b)}
}

func (_c *MockFINSClient_WriteBytes_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, b []byte)) *MockFINSClient_WriteBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_WriteBytes_Call) Return(err error) *MockFINSClient_WriteBytes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_WriteBytes_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, b []byte) error) *MockFINSClient_WriteBytes_Call {
	_c.Call.Return(run)
	return _c
}

// WriteString provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) WriteString(ctx context.Context, memoryArea byte, address uint16, s string) error {
	ret := _mock.Called(ctx, memoryArea, address, s)

	if len(ret) == 0 {
		panic("no return value specified for WriteString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, string) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_WriteString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteString'
type MockFINSClient_WriteString_Call struct {
	*mock.Call
}

// WriteString is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - s string
func (_e *MockFINSClient_Expecter) WriteString(ctx interface{}, memoryArea interface{}, address interface{}, s interface{}) *MockFINSClient_WriteString_Call {
	return &MockFINSClient_WriteString_Call{Call: _e.mock.On("WriteString", ctx, memoryArea, address, s)}
}

func (_c *MockFINSClient_WriteString_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, s string)) *MockFINSClient_WriteString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_WriteString_Call) Return(err error) *MockFINSClient_WriteString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_WriteString_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, s string) error) *MockFINSClient_WriteString_Call {
	_c.Call.Return(run)
	return _c
}

// WriteWords provides a mock function for the type MockFINSClient
func (_mock *MockFINSClient) WriteWords(ctx context.Context, memoryArea byte, address uint16, data []uint16) error {
	ret := _mock.Called(ctx, memoryArea, address, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteWords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, byte, uint16, []uint16) error); ok {
		r0 = returnFunc(ctx, memoryArea, address, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFINSClient_WriteWords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteWords'
type MockFINSClient_WriteWords_Call struct {
	*mock.Call
}

// WriteWords is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryArea byte
//   - address uint16
//   - data []uint16
func (_e *MockFINSClient_Expecter) WriteWords(ctx interface{}, memoryArea interface{}, address interface{}, data interface{}) *MockFINSClient_WriteWords_Call {
	return &MockFINSClient_WriteWords_Call{Call: _e.mock.On("WriteWords", ctx, memoryArea, address, data)}
}

func (_c *MockFINSClient_WriteWords_Call) Run(run func(ctx context.Context, memoryArea byte, address uint16, data []uint16)) *MockFINSClient_WriteWords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		var arg3 []uint16
		if args[3] != nil {
			arg3 = args[3].([]uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFINSClient_WriteWords_Call) Return(err error) *MockFINSClient_WriteWords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFINSClient_WriteWords_Call) RunAndReturn(run func(ctx context.Context, memoryArea byte, address uint16, data []uint16) error) *MockFINSClient_WriteWords_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlugin creates a new instance of MockPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlugin {
	mock := &MockPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlugin is an autogenerated mock type for the Plugin type
type MockPlugin struct {
	mock.Mock
}

type MockPlugin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlugin) EXPECT() *MockPlugin_Expecter {
	return &MockPlugin_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockPlugin
func (_mock *MockPlugin) Initialize(client *Client) error {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Client) error); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlugin_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockPlugin_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - client *Client
func (_e *MockPlugin_Expecter) Initialize(client interface{}) *MockPlugin_Initialize_Call {
	return &MockPlugin_Initialize_Call{Call: _e.mock.On("Initialize", client)}
}

func (_c *MockPlugin_Initialize_Call) Run(run func(client *Client)) *MockPlugin_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Client
		if args[0] != nil {
			arg0 = args[0].(*Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlugin_Initialize_Call) Return(err error) *MockPlugin_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlugin_Initialize_Call) RunAndReturn(run func(client *Client) error) *MockPlugin_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockPlugin
func (_mock *MockPlugin) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPlugin_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPlugin_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPlugin_Expecter) Name() *MockPlugin_Name_Call {
	return &MockPlugin_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPlugin_Name_Call) Run(run func()) *MockPlugin_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlugin_Name_Call) Return(s string) *MockPlugin_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPlugin_Name_Call) RunAndReturn(run func() string) *MockPlugin_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionPlugin creates a new instance of MockConnectionPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionPlugin {
	mock := &MockConnectionPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionPlugin is an autogenerated mock type for the ConnectionPlugin type
type MockConnectionPlugin struct {
	mock.Mock
}

type MockConnectionPlugin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionPlugin) EXPECT() *MockConnectionPlugin_Expecter {
	return &MockConnectionPlugin_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type MockConnectionPlugin
func (_mock *MockConnectionPlugin) Initialize(client *Client) error {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Client) error); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionPlugin_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockConnectionPlugin_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - client *Client
func (_e *MockConnectionPlugin_Expecter) Initialize(client interface{}) *MockConnectionPlugin_Initialize_Call {
	return &MockConnectionPlugin_Initialize_Call{Call: _e.mock.On("Initialize", client)}
}

func (_c *MockConnectionPlugin_Initialize_Call) Run(run func(client *Client)) *MockConnectionPlugin_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Client
		if args[0] != nil {
			arg0 = args[0].(*Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionPlugin_Initialize_Call) Return(err error) *MockConnectionPlugin_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionPlugin_Initialize_Call) RunAndReturn(run func(client *Client) error) *MockConnectionPlugin_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockConnectionPlugin
func (_mock *MockConnectionPlugin) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConnectionPlugin_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockConnectionPlugin_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockConnectionPlugin_Expecter) Name() *MockConnectionPlugin_Name_Call {
	return &MockConnectionPlugin_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockConnectionPlugin_Name_Call) Run(run func()) *MockConnectionPlugin_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionPlugin_Name_Call) Return(s string) *MockConnectionPlugin_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConnectionPlugin_Name_Call) RunAndReturn(run func() string) *MockConnectionPlugin_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnected provides a mock function for the type MockConnectionPlugin
func (_mock *MockConnectionPlugin) OnConnected(client *Client) error {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for OnConnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Client) error); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionPlugin_OnConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnected'
type MockConnectionPlugin_OnConnected_Call struct {
	*mock.Call
}

// OnConnected is a helper method to define mock.On call
//   - client *Client
func (_e *MockConnectionPlugin_Expecter) OnConnected(client interface{}) *MockConnectionPlugin_OnConnected_Call {
	return &MockConnectionPlugin_OnConnected_Call{Call: _e.mock.On("OnConnected", client)}
}

func (_c *MockConnectionPlugin_OnConnected_Call) Run(run func(client *Client)) *MockConnectionPlugin_OnConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Client
		if args[0] != nil {
			arg0 = args[0].(*Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionPlugin_OnConnected_Call) Return(err error) *MockConnectionPlugin_OnConnected_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionPlugin_OnConnected_Call) RunAndReturn(run func(client *Client) error) *MockConnectionPlugin_OnConnected_Call {
	_c.Call.Return(run)
	return _c
}

// OnDisconnected provides a mock function for the type MockConnectionPlugin
func (_mock *MockConnectionPlugin) OnDisconnected(client *Client, err error) error {
	ret := _mock.Called(client, err)

	if len(ret) == 0 {
		panic("no return value specified for OnDisconnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Client, error) error); ok {
		r0 = returnFunc(client, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionPlugin_OnDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDisconnected'
type MockConnectionPlugin_OnDisconnected_Call struct {
	*mock.Call
}

// OnDisconnected is a helper method to define mock.On call
//   - client *Client
//   - err error
func (_e *MockConnectionPlugin_Expecter) OnDisconnected(client interface{}, err interface{}) *MockConnectionPlugin_OnDisconnected_Call {
	return &MockConnectionPlugin_OnDisconnected_Call{Call: _e.mock.On("OnDisconnected", client, err)}
}

func (_c *MockConnectionPlugin_OnDisconnected_Call) Run(run func(client *Client, err error)) *MockConnectionPlugin_OnDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Client
		if args[0] != nil {
			arg0 = args[0].(*Client)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionPlugin_OnDisconnected_Call) Return(err1 error) *MockConnectionPlugin_OnDisconnected_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockConnectionPlugin_OnDisconnected_Call) RunAndReturn(run func(client *Client, err error) error) *MockConnectionPlugin_OnDisconnected_Call {
	_c.Call.Return(run)
	return _c
}
